version: '3.8'
services:
  wallet:
    image: lthn/wallet
    platform: linux/amd64
    network_mode: host
    tty: true
    volumes:
      - "./wallets:/wallets"
  exit-node:
    platform: linux/amd64
    build:
      context: .
      args:
        - PORT:8080
        - BRANCH=v1
        - PROVIDERID=1234
    volumes:
      - "./data/vpn/etc:/opt/lthn/etc"
    command:
      - run
    container_name: lethean-vpn
    env_file:
      - server/config.env
    ports:
      - "8080:3000"
      - "8081:3001"
      - "14660:14660"

